name: Run foo1
run-name: ${{ github.actor }} is testing out foo1 🚀
on: 
  push:
    paths:
      - 'packages/clients/client3/**'
    branches:
      - foo
jobs:
  foo1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "foo1"
